import{i as f}from"./assets/vendor-38388549.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&c(o)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const u=document.querySelector(".js-images-container");function m(a){const r=a.map(t=>`<li class="gallery-item">
        <a href="${t.largeImageURL}" target="_blank" rel="noopener noreferrer">
          <article>
            <img src="${t.webformatURL}" alt="${t.tags}" width="360" height="200"/>
            <div class="text-content-box">
                <p class="image-text"><span class="image-title">Likes</span> ${t.likes}</p>
                <p class="image-text"><span class="image-title">Views</span> ${t.views}</p>
                <p class="image-text"><span class="image-title">Comments</span> ${t.comments}</p>
                <p class="image-text"><span class="image-title">Downloads</span> ${t.downloads}</p>
            </div>
          </article>
        </a>
      </li>`).join("");u.insertAdjacentHTML("beforeend",r)}function l(){u.innerHTML=""}g;const h="https://pixabay.com/api/";class d{constructor(){this.searchQuery="",this.page=1}fetchImages(){const r=`${h}?key=42616276-59c99055eec179e7b1bf68313&q=${this.searchQuery}&lang=en&per_page=15&Page=${this.page}`;return fetch(r).then(t=>t.json()).then(t=>(t.total===0&&p(),this.incrementPage(),t.hits))}incrementPage(){this.page+=1}resetPage(){this.page=1}get query(){return this.searchQuery}set query(r){this.searchQuery=r}}function p(a){f.show({message:"Sorry, there are no images matching <br> your search query. Please, try again!",position:"topRight",timeout:5e3,backgroundColor:"#ef4040",messageColor:"#ffffff",messageSize:"12",close:!0,closeOnEscape:!0,progressBarColor:"#B51B1B",progressBar:!0,layout:2,maxWidth:432,maxHeigth:88,animateInside:!0,iconUrl:"../css/x-octagon.svg",transitionIn:"fadeInRight",transitionOut:"fadeOutRight"})}const i={searchForm:document.querySelector(".js-search-form"),waitingText:document.querySelector(".js-waiting-text")},n=new d;i.searchForm.addEventListener("submit",y);function y(a){if(a.preventDefault(),i.waitingText.style.display="block",n.query=a.currentTarget.elements.query.value,n.resetPage(),n.query===""){p(),l();return}n.fetchImages(searchQuery).then(r=>{x(),l(),m(r)}).catch(r=>{console.log(r)}),i.searchForm.reset()}function x(){i.waitingText.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
