import{i as m,S as f}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&c(o)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const g=document.querySelector(".js-images-container");function h(a){const s=a.map(t=>`<li class="gallery-item">
          <a href="${t.largeImageURL}">
            <img src="${t.webformatURL}" alt="${t.tags}" width="360" height="200"/>
            <div class="text-content-box">
                <p class="image-text"><span class="image-title">Likes</span> ${t.likes}</p>
                <p class="image-text"><span class="image-title">Views</span> ${t.views}</p>
                <p class="image-text"><span class="image-title">Comments</span> ${t.comments}</p>
                <p class="image-text"><span class="image-title">Downloads</span> ${t.downloads}</p>
            </div>
        </a>
      </li>`).join("");g.insertAdjacentHTML("beforeend",s)}function l(){g.innerHTML=""}const d="https://pixabay.com/api/";class y{constructor(){this.searchQuery="",this.page=1}fetchImages(){const s=`${d}?key=42616276-59c99055eec179e7b1bf68313&q=${this.searchQuery}&lang=en&per_page=15&Page=${this.page}`;return fetch(s).then(t=>t.json()).then(t=>(t.total===0&&p(),this.incrementPage(),t.hits))}incrementPage(){this.page+=1}resetPage(){this.page=1}get query(){return this.searchQuery}set query(s){this.searchQuery=s}}function p(a){m.show({message:"Sorry, there are no images matching <br> your search query. Please, try again!",position:"topRight",timeout:5e3,backgroundColor:"#ef4040",messageColor:"#ffffff",messageSize:"12",close:!0,closeOnEscape:!0,progressBarColor:"#B51B1B",progressBar:!0,layout:2,maxWidth:432,maxHeigth:88,animateInside:!0,iconUrl:"./assets/x-octagon.svg",transitionIn:"fadeInRight",transitionOut:"fadeOutRight"})}const n={searchForm:document.querySelector(".js-search-form"),waitingText:document.querySelector(".js-waiting-text")},i=new y;n.searchForm.addEventListener("submit",x);function x(a){if(a.preventDefault(),n.waitingText.style.display="block",i.query=a.currentTarget.elements.query.value,i.resetPage(),i.query===""){p(),u(),l();return}i.fetchImages(searchQuery).then(s=>{u(),l(),h(s),document.querySelector(".images"),new f(".images a",{captionPosition:"bottom",captionDelay:250,captionsData:"alt"})}).catch(s=>{console.log(s)}),n.searchForm.reset()}function u(){n.waitingText.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
